site_name: Georgi's site
site_url: https://gessha.dev

nav:
  - Home: index.md
  - About: about.md
  - Now: now.md
  - Projects: projects.md
  - Blog: blog.md

# theme:
  # name: mkdocs
  # locale: en

theme:
  name: null
  custom_dir: 'theme'

plugins:
  - blogging:
      dirs:
        - posts