site_name: Georgi's site
site_url: https://gessha.dev

nav:
  - Home: index.md
  - About: index.md
  - Now: now.md
  - Projects: projects.md
  - Blog: blog.md

theme:
  name: mkdocs
  locale: en

plugins:
  - blogging:
      dirs:
        - posts